const js = require('@eslint/js');
const globals = require('globals');
const html = require('eslint-plugin-html');

module.exports = [
    js.configs.recommended,
    {
        files: ['**/*.js', '**/*.html'],
        plugins: {
            html: html,
        },
        languageOptions: {
            globals: {
                ...globals.browser,
                ...globals.node,
                CMSAdmin: 'readonly',
                firebase: 'readonly',
                db: 'writable',
                auth: 'writable',
                showToast: 'readonly',
                showLoading: 'readonly',
                schoolData: 'writable',
                schoolDoc: 'writable',
                withSchool: 'readonly',
                storage: 'readonly',
                schoolId: 'readonly',
                Chart: 'readonly',
                lucide: 'readonly',
                html2pdf: 'readonly',
                bootstrap: 'readonly',
                jQuery: 'readonly',
                $: 'readonly',
                initSearchableSelect: 'readonly',
                showToastGlobal: 'readonly',
                exportToCSV: 'readonly',
                bootstrapModal: 'readonly',
                idTemplate_modern: 'readonly',
                idTemplate_pro: 'readonly',
                idTemplate_classic: 'readonly',
                generateBarcode: 'readonly',
                XLSX: 'readonly',
                erpState: 'writable',
                setLoading: 'readonly',
                openCmsModal: 'readonly',
                closeCmsModal: 'readonly',
                CURRENT_SCHOOL_ID: 'readonly',
                html2canvas: 'readonly',
                showSection: 'readonly',
                loadScheduleGrid: 'readonly',
            },
            ecmaVersion: 'latest',
            sourceType: 'script',
        },
        rules: {
            'no-unused-vars': 'warn',
            'no-console': 'off',
            indent: 'off',
            quotes: ['error', 'single'],
            semi: ['error', 'always'],
            'no-redeclare': 'off',
        },
    },
    {
        ignores: [
            'node_modules/**',
            'temp_question_tool/**',
            'temp_super_admin/**',
            'pdf/**',
            'images/**',
            '.git/**',
            '.firebase/**',
            'scripts/**',
            'portal/question-formatter/**',
        ],
    },
];
