const js = require('@eslint/js');
const globals = require('globals');
const html = require('eslint-plugin-html');

module.exports = [
    js.configs.recommended,
    {
        files: ['**/*.js', '**/*.html'],
        plugins: {
            html: html,
        },
        languageOptions: {
            globals: {
                ...globals.browser,
                ...globals.node,
                CMSAdmin: 'readonly',
                firebase: 'readonly',
                db: 'writable',
                auth: 'writable',
                showToast: 'readonly',
                showLoading: 'readonly',
                schoolData: 'writable',
                schoolDoc: 'writable',
                schoolRef: 'writable',
                withSchool: 'readonly',
                storage: 'readonly',
                schoolId: 'readonly',
                Chart: 'readonly',
                lucide: 'readonly',
                html2pdf: 'readonly',
                bootstrap: 'readonly',
                jQuery: 'readonly',
                $: 'readonly',
                initSearchableSelect: 'readonly',
                showToastGlobal: 'readonly',
                exportToCSV: 'readonly',
                bootstrapModal: 'readonly',
                idTemplate_modern: 'readonly',
                idTemplate_pro: 'readonly',
                idTemplate_classic: 'readonly',
                generateBarcode: 'readonly',
                XLSX: 'readonly',
                erpState: 'writable',
                setLoading: 'readonly',
                openCmsModal: 'readonly',
                closeCmsModal: 'readonly',
                CURRENT_SCHOOL_ID: 'readonly',
                html2canvas: 'readonly',
                showSection: 'readonly',
                loadScheduleGrid: 'readonly',
                jspdf: 'readonly',
                currentReceiptId: 'writable',
                loadRevertedPayments: 'readonly',
                loadMonthlyPaymentView: 'readonly',
                revertPayment: 'readonly',
                exportReceiptPDF: 'readonly',
                closeReceipt: 'readonly',
                printReceipt: 'readonly',
                initERPCertificates: 'readonly',
                loadCertSessions: 'readonly',
                loadCertClasses: 'readonly',
                loadCertSections: 'readonly',
                loadCertStudents: 'readonly',
                populateCertStudent: 'readonly',
                generateCertificate: 'readonly',
                printCert: 'readonly',
                exportCertPDF: 'readonly',
                closeCertPreview: 'readonly',
                loadCertHistory: 'readonly',
                reprintCert: 'readonly',
                exportHistoryCertPDF: 'readonly',
                voidCert: 'readonly',
                firebase: 'readonly',
                loadDemandSessions: 'readonly',
                loadDemandClasses: 'readonly',
                loadDemandSections: 'readonly',
                loadDemandStudents: 'readonly',
                generateBatchDemandReceipts: 'readonly',
                printDemandReceipts: 'readonly',
                exportDemandPDF: 'readonly',
                saveStudentRemarks: 'readonly',
                sendSmsAlert: 'readonly',
                initERPParentLogin: 'readonly',
                searchStudentsForParentLogin: 'readonly',
                openCreateParentLoginModal: 'readonly',
                openEditParentLoginModal: 'readonly',
                saveParentLogin: 'readonly',
                toggleParentLoginStatus: 'readonly',
                confirmDeleteParentLogin: 'readonly',
                generatePassword: 'readonly',
                closeParentLoginModal: 'readonly',
                toggleAllParentLoginSections: 'readonly',
                loadStudentCertificates: 'readonly',
                requestCertificate: 'readonly',
                downloadCertPDF: 'readonly',
                viewStudentCertPDF: 'readonly',
                downloadStudentReceiptPDF: 'readonly',
                switchStudent: 'readonly',
                openChangePwdModal: 'readonly',
                closeChangePwdModal: 'readonly',
                submitChangePassword: 'readonly',
                openAdminChangePwdModal: 'readonly',
                closeAdminChangePwdModal: 'readonly',
                submitAdminChangePassword: 'readonly',
                switchLoginMode: 'readonly',
                togglePassword: 'readonly',
                loginAsGuest: 'readonly',
            },
            ecmaVersion: 'latest',
            sourceType: 'script',
        },
        rules: {
            'no-unused-vars': 'warn',
            'no-console': 'off',
            indent: 'off',
            quotes: ['error', 'single'],
            semi: ['error', 'always'],
            'no-redeclare': 'off',
        },
    },
    {
        ignores: [
            'node_modules/**',
            'temp_question_tool/**',
            'temp_super_admin/**',
            'pdf/**',
            'images-archive/**',
            '.git/**',
            '.firebase/**',
            'scripts/**',
            'portal/question-formatter/**',
        ],
    },
];
